wip
Signed-off-by: José Guilherme Vanz <jguilhermevanz@suse.com>

diff --git a/.github/workflows/release-tag.yaml b/.github/workflows/release-tag.yaml
--- a/.github/workflows/release-tag.yaml
+++ b/.github/workflows/release-tag.yaml
@@ -71,14 +71,82 @@ jobs:
         run: echo "$MATRIX_CONTEXT"
 
   release-tag:
-    name: release-tag
+    name: Tag and push, triggering release
     needs: [calculate-policy-matrix, dump_contexts_to_log]
-    uses: jvanz/github-actions/.github/workflows/reusable-release-tag.yml@monorepo
+    if: >
+      github.event.pull_request.merged == true &&
+      contains(github.event.pull_request.labels.*.name, 'TRIGGER-RELEASE') ||
+      github.event.inputs.trigger_release == 'true'
+    runs-on: ubuntu-latest
+    continue-on-error: true
     concurrency:
       group: ${{ github.workflow }}-${{ matrix.policy-working-dir }}
     strategy:
       matrix:
         policy-working-dir: ${{ fromJSON(needs.calculate-policy-matrix.outputs.policy_working_dirs) }}
-    with:
-      policy-working-dir: ${{ matrix.policy-working-dir }}
-      continue-on-error: true # If some policy tagging fail, the other should continue
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+        with:
+          fetch-depth: 0 # also checkout tags
+
+      - name: Extract version from metadata.yml
+        id: extract-version
+        shell: bash
+        run: |
+          POLICY_DIR="${{ matrix.policy-working-dir }}"
+          POLICY_NAME=""
+          FILES=("metadata.yml" "metadata.yaml")
+          VERSION=""
+          for F in "${FILES[@]}"; do
+            FILE="$F"
+            if [ -n "$POLICY_DIR" ]; then
+              if [ -f "$POLICY_DIR" ]; then
+                echo "The policy directory does not exists: $POLICY_DIR"
+                exit 1
+              fi
+              FILE="$POLICY_DIR/$F"
+              # policy dir can have multiple directories. Assume the last one
+              # to be the policy-name
+              POLICY_NAME="$(basename $POLICY_DIR)"
+            fi
+            if [ -f "$FILE" ]; then
+              VERSION="v$(yq e '.annotations."io.kubewarden.policy.version"' $FILE)"
+              if [ -z "$VERSION" ]; then
+                echo "annotation 'io.kubewarden.policy.version' is missing in $FILE"
+                exit 1
+              fi
+              if  [ -n "$POLICY_NAME" ]; then
+                VERSION="$POLICY_NAME/$VERSION"
+              fi
+              echo "found version $VERSION"
+              echo "VERSION=$VERSION" >> $GITHUB_ENV
+              exit 0
+            fi
+          done
+          echo "Error: metadata.yml or metadata.yaml not found" >&2
+          exit 1
+
+      - name: Configure Git author
+        run: |
+          git config user.name "Kubewarden bot"
+          git config user.email "cncf-kubewarden-maintainers@lists.cncf.io"
+
+      - name: Create and push tag
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          git tag -a "$VERSION" -m "Release version $VERSION"
+          git push origin "$VERSION"
+
+      - name: Trigger release workflow
+        run: gh workflow run release.yml --ref "$VERSION"
+        env:
+          GH_TOKEN: ${{ github.token }}
+
+      - name: Delete branch corresponding to the PR
+        if: github.event.pull_request.head.ref != 'main'
+        run: |
+          git push origin --delete ${{ github.event.pull_request.head.ref }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
